name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: swift build --disable-sandbox --configuration release

      - name: Test
        run: set -o pipefail && swift test 2>&1 | .build/release/xcbeautify
