on:
  push:
    tags:
      - '*'
name: Release
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  macos:
    name: Release
    runs-on: macos-latest
    needs: create_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Package
        run: make package
      - name: Darwin Universal
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.steps.create_release.outputs.upload_url }}
          asset_path: .build/apple/Products/Release/xcbeautify.zip
          asset_name: xcbeautify-${{ github.ref }}-universal-apple-macosx.zip
          asset_content_type: application/zip
      - name: Darwin x86_64
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.steps.create_release.outputs.upload_url }}
          asset_path: .build/x86_64-apple-macosx/release/xcbeautify.zip
          asset_name: xcbeautify-${{ github.ref }}-x86_64-apple-macosx.zip
          asset_content_type: application/zip
      - name: Darwin arm64
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.steps.create_release.outputs.upload_url }}
          asset_path: .build/arm64-apple-macosx/release/xcbeautify.zip
          asset_name: xcbeautify-${{ github.ref }}-arm64-apple-macosx.zip
          asset_content_type: application/zip
      - name: Publish To CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          bundle install
          bundle exec pod trunk push --allow-warnings
  ubuntu:
    name: Release Linux
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package Linux x86_64
        run: make package-linux-x86_64
      - name: Upload Release Asset for Linux x86_64
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.steps.create_release.outputs.upload_url }}
          asset_path: .build/x86_64-unknown-linux-gnu/release/xcbeautify.tar.xz
          asset_name: xcbeautify-${{ github.ref }}-x86_64-unknown-linux-gnu.tar.xz
          asset_content_type: application/x-xz
